---
api service v1:
  - local:
      url: '127.0.0.1/api/v1'
      port: 8084
      auth: basic
  - local docker:
      url: '127.0.0.1'
      port: 8085
      auth: no

api service v2:
  local:
    url: 'http:/localhost/api/v2'
    port: 8085
    auth:
      type: sasl
      username: ENVVAR_USER_NAME
      password: ENVVAR_USER_PASSWORD

database service:
  - provider 1:
      url:
      port:
      auth:
  - provider 2:
      key: value

proxy:
  url: 'https:/intranet.proxy.com'
  port: 2345
